//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The copy POCO of the Characteristic of products class model
    /// </summary>
    public partial class ProductCharacteristic
    {

        /// <summary>
        /// Gets or sets the product characteristic identifier.
        /// </summary>
        /// <value>
        /// The product characteristic identifier.
        /// </value>
        public int ProductCharacteristicID { get; set; }

        /// <summary>
        /// Gets or sets the product identifier.
        /// </summary>
        /// <value>
        /// The product identifier.
        /// </value>
        public int ProductID { get; set; }

        /// <summary>
        /// Gets or sets the characteristic identifier.
        /// </summary>
        /// <value>
        /// The characteristic identifier.
        /// </value>
        public int CharacteristicID { get; set; }

        /// <summary>
        /// Gets or sets the characteristic value.
        /// </summary>
        /// <value>
        /// The characteristic value.
        /// </value>
        public string CharacteristicValue { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is active.
        /// </summary>
        /// <value>
        ///   <c>true</c> if this instance is active; otherwise, <c>false</c>.
        /// </value>
        public bool IsActive { get; set; }
    
        public virtual Characteristic Characteristic { get; set; }
        public virtual Product Product { get; set; }
    }
}
