//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Entity
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    ///The ShoppingCart class model
    /// </summary>
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.ProductCarts = new HashSet<ProductCart>();
        }

        /// <summary>
        /// Gets or sets the shopping cart identifier.
        /// </summary>
        /// <value>
        /// The shopping cart identifier.
        /// </value>
        public string ShoppingCartID { get; set; }

        /// <summary>
        /// Gets or sets the owner.
        /// </summary>
        /// <value>
        /// The shoppingcart owner.
        /// </value>
        public string Owner { get; set; }

        /// <summary>
        /// Gets or sets the phone.
        /// </summary>
        /// <value>
        /// The user/owner phone number.
        /// </value>
        public string Phone { get; set; }
    
        public virtual ICollection<ProductCart> ProductCarts { get; set; }
    }
}
